services:
  gateway:
    image: gateway:0.0.1-SNAPSHOT
    ports:
      - "8080:8000"
  resourceserver:
    image: resourceserver:0.0.1-SNAPSHOT
  auth:
    image: authservice:0.0.1-SNAPSHOT
    ports:
      - "9000:9000"
