spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: example-route
            uri: http://resourceserver:8081/
            predicates:
              - Path=/api/**
            filters:
              - RewritePath=/api/?(?<segment>.*), /$\{segment}
